name: models_dart
description: Models package
version: 2.0.0-pre-version
author: Markus Krebs <markuskrebs93@gmail.com>
homepage: https://www.movementfam.de
repository: https://github.com/movementfamily-e-v/models_dart

environment:
  sdk: ">=2.10.0 <3.0.0"

# dependencies
dependencies:
  # parsing html code
  # BSD-License
  # https://pub.dev/packages/html_unescape
  html_unescape: ^1.0.2

  # datetime handling
  # BSD-License
  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # hive
  # lightweight storage
  # Apache 2 License
  # https://pub.dev/packages/hive
  hive: ^2.0.0

# dev dependencies
dev_dependencies:
  # linter rules
  pedantic: ^1.11.0
  # hive generation
  hive_generator: ^1.0.0
  build_runner: ^1.11.0