name: models_dart
description: Models
version: 1.0.1
author: Markus Krebs <markuskrebs93@gmail.com>
homepage: https://www.movementfam.de
repository: https://github.com/movementfamily-e-v/models_dart

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

# dependencies
dependencies:
  # flutter sdk
  flutter:
    sdk: flutter

  # parsing html code
  # BSD-License
  # https://pub.dev/packages/html_unescape
  html_unescape: ^1.0.2

  # datetime handling
  # BSD-License
  # https://pub.dev/packages/intl
  intl: ^0.16.1

# dev dependencies
dev_dependencies:
  # linter rules
  pedantic: ^1.9.2